// <auto-generated />
using System;
using CanastaCR.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CanastaCR.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616133928_MakePriceReportChainLevel")]
    partial class MakePriceReportChainLevel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CanastaCR.Core.Entities.PantryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastPurchasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MinThreshold")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("PantryItems");
                });

            modelBuilder.Entity("CanastaCR.Core.Entities.PriceReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Chain")
                        .HasColumnType("integer");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReportedById")
                        .HasColumnType("uuid");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<Guid?>("StoreId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReportedById");

                    b.HasIndex("StoreId");

                    b.HasIndex("ProductId", "StoreId", "ReportedAt");

                    b.ToTable("PriceReports");
                });

            modelBuilder.Entity("CanastaCR.Core.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasFilter("\"Barcode\" IS NOT NULL");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CanastaCR.Core.Entities.ShoppingList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingLists");
                });

            modelBuilder.Entity("CanastaCR.Core.Entities.ShoppingListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPurchased")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<Guid>("ShoppingListId")
                        .HasColumnType("uuid");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShoppingListId");

                    b.ToTable("ShoppingListItems");
                });

            modelBuilder.Entity("CanastaCR.Core.Entities.ShoppingTrip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedSavings")
                        .HasColumnType("numeric");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalSpent")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingTrips");
                });

            modelBuilder.Entity("CanastaCR.Core.Entities.ShoppingTripItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ShoppingTripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShoppingTripId");

                    b.ToTable("ShoppingTripItems");
                });

            modelBuilder.Entity("CanastaCR.Core.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<int>("Chain")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Lng")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            Address = "Multiplaza Escazú",
                            Chain = 0,
                            City = "Escazú",
                            Lat = 9.9196000000000009,
                            Lng = -84.134900000000002,
                            Name = "AutoMercado Escazú"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            Address = "Av. Central, San Pedro",
                            Chain = 0,
                            City = "San José",
                            Lat = 9.9347999999999992,
                            Lng = -84.048900000000003,
                            Name = "AutoMercado San Pedro"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            Address = "La Uruca",
                            Chain = 1,
                            City = "San José",
                            Lat = 9.9608000000000008,
                            Lng = -84.101299999999995,
                            Name = "Más x Menos La Uruca"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000004"),
                            Address = "Centro Cartago",
                            Chain = 1,
                            City = "Cartago",
                            Lat = 9.8632000000000009,
                            Lng = -83.919799999999995,
                            Name = "Más x Menos Cartago"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000005"),
                            Address = "Alajuela Centro",
                            Chain = 2,
                            City = "Alajuela",
                            Lat = 10.0162,
                            Lng = -84.211600000000004,
                            Name = "MaxiPalí Alajuela"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000006"),
                            Address = "Heredia Centro",
                            Chain = 2,
                            City = "Heredia",
                            Lat = 9.9984999999999999,
                            Lng = -84.117099999999994,
                            Name = "MaxiPalí Heredia"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000007"),
                            Address = "Tibás",
                            Chain = 3,
                            City = "San José",
                            Lat = 9.9741999999999997,
                            Lng = -84.082099999999997,
                            Name = "MegaSuper Tibás"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000008"),
                            Address = "Desamparados",
                            Chain = 3,
                            City = "San José",
                            Lat = 9.9031000000000002,
                            Lng = -84.076599999999999,
                            Name = "MegaSuper Desamparados"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000009"),
                            Address = "La Uruca",
                            Chain = 4,
                            City = "San José",
                            Lat = 9.9571000000000005,
                            Lng = -84.110699999999994,
                            Name = "PriceSmart San José"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000010"),
                            Address = "Alajuela",
                            Chain = 4,
                            City = "Alajuela",
                            Lat = 10.0198,
                            Lng = -84.2089,
                            Name = "PriceSmart Alajuela"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000011"),
                            Address = "La Uruca",
                            Chain = 5,
                            City = "San José",
                            Lat = 9.9611999999999998,
                            Lng = -84.108900000000006,
                            Name = "Walmart San José"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000012"),
                            Address = "Alajuela Centro",
                            Chain = 5,
                            City = "Alajuela",
                            Lat = 10.0175,
                            Lng = -84.214200000000005,
                            Name = "Walmart Alajuela"
                        });
                });

            modelBuilder.Entity("CanastaCR.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReputationPoints")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CanastaCR.Core.Entities.UserPreferences", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("HomeLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("HomeLng")
                        .HasColumnType("double precision");

                    b.Property<int>("MaxStoresPerTrip")
                        .HasColumnType("integer");

                    b.Property<decimal>("TravelCostThreshold")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("UserId");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("CanastaCR.Core.Entities.PantryItem", b =>
                {
                    b.HasOne("CanastaCR.Core.Entities.Product", "Product")
                        .WithMany("PantryItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CanastaCR.Core.Entities.User", "User")
                        .WithMany("PantryItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CanastaCR.Core.Entities.PriceReport", b =>
                {
                    b.HasOne("CanastaCR.Core.Entities.Product", "Product")
                        .WithMany("PriceReports")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CanastaCR.Core.Entities.User", "ReportedBy")
                        .WithMany("PriceReports")
                        .HasForeignKey("ReportedById");

                    b.HasOne("CanastaCR.Core.Entities.Store", "Store")
                        .WithMany("PriceReports")
                        .HasForeignKey("StoreId");

                    b.Navigation("Product");

                    b.Navigation("ReportedBy");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("CanastaCR.Core.Entities.ShoppingList", b =>
                {
                    b.HasOne("CanastaCR.Core.Entities.User", "User")
                        .WithMany("ShoppingLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CanastaCR.Core.Entities.ShoppingListItem", b =>
                {
                    b.HasOne("CanastaCR.Core.Entities.Product", "Product")
                        .WithMany("ShoppingListItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CanastaCR.Core.Entities.ShoppingList", "ShoppingList")
                        .WithMany("Items")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("CanastaCR.Core.Entities.ShoppingTrip", b =>
                {
                    b.HasOne("CanastaCR.Core.Entities.Store", "Store")
                        .WithMany("ShoppingTrips")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CanastaCR.Core.Entities.User", "User")
                        .WithMany("ShoppingTrips")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CanastaCR.Core.Entities.ShoppingTripItem", b =>
                {
                    b.HasOne("CanastaCR.Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CanastaCR.Core.Entities.ShoppingTrip", "ShoppingTrip")
                        .WithMany("Items")
                        .HasForeignKey("ShoppingTripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ShoppingTrip");
                });

            modelBuilder.Entity("CanastaCR.Core.Entities.UserPreferences", b =>
                {
                    b.HasOne("CanastaCR.Core.Entities.User", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("CanastaCR.Core.Entities.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CanastaCR.Core.Entities.Product", b =>
                {
                    b.Navigation("PantryItems");

                    b.Navigation("PriceReports");

                    b.Navigation("ShoppingListItems");
                });

            modelBuilder.Entity("CanastaCR.Core.Entities.ShoppingList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CanastaCR.Core.Entities.ShoppingTrip", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CanastaCR.Core.Entities.Store", b =>
                {
                    b.Navigation("PriceReports");

                    b.Navigation("ShoppingTrips");
                });

            modelBuilder.Entity("CanastaCR.Core.Entities.User", b =>
                {
                    b.Navigation("PantryItems");

                    b.Navigation("Preferences");

                    b.Navigation("PriceReports");

                    b.Navigation("ShoppingLists");

                    b.Navigation("ShoppingTrips");
                });
#pragma warning restore 612, 618
        }
    }
}
